In [1]:
# Parts of this notebook are adapted from the code accompanying Moon and Lazar (2023).

In [1]:
import sys
import os
sys.path.append(os.path.abspath("..")) 
sys.path.append(os.path.abspath("../../source"))
from TDA_Testing import *
import json
import pandas as pd
import pickle
def savepkl(obj, path):
    with open(path, 'wb') as f:
        pickle.dump(obj, f)
def loadpkl(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

In [2]:
# import PD - json, each pds are saved as unnamed array
with open("../../data/json/npc=50_nset=100torus_pd.json") as f:
    torus_pd = json.load(f)
    
torus_pdlist=[]
for ii in range(len(torus_pd)):
    torus_pdsublist = []
    for jj in range(len(torus_pd[0])):
        torus_pddat = np.array(torus_pd[ii][jj])
        torus_pdmat = np.transpose( np.resize(torus_pddat, (3,int(len(torus_pddat)/3)) ) )
        torus_pddim1 = torus_pdmat[torus_pdmat[:,0]==1,1:]
        torus_pdsublist.append(torus_pddim1)
    torus_pdlist.append(torus_pdsublist)

In [3]:
# simulation parameters
npc=50
nset=100
sig=[0.01,0.02,0.03,0.04,0.05] #except 0 
nsig=len(sig)
comb = np.array(list(combinations(range(nset), 2)))
random.seed(42)
ind=random.sample(range(len(comb)),nset)

In [ ]:
selected_pairs1 = comb[ind]
np.savetxt("selected_pairs_torus_diffnoise.csv", selected_pairs, delimiter=",", fmt="%d")

# Aggregation testing

In [13]:
# linear
random.seed(42)
func_weight = function_weight("Poly", poly_order=1)
Agg_linear_opt=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    print(np.sum(Agg_linear_opt==1,axis=1)/nset) 
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result = Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_linear_opt[kk,jj] = test_result

0
[0. 0. 0. 0. 0.]
1
[0.97 0.   0.   0.   0.  ]
2
[0.97 1.   0.   0.   0.  ]
3
[0.97 1.   1.   0.   0.  ]
4
[0.97 1.   1.   1.   0.  ]


In [18]:
savepkl(np.sum(Agg_linear_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_linear_opt.pkl')
np.sum(Agg_linear_opt==1,axis=1)/nset 

array([0.97, 1.  , 1.  , 1.  , 1.  ])

In [14]:
#root_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=0.5)
Agg_root_opt=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    print(np.sum(Agg_root_opt==1,axis=1)/nset)
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result =  Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_root_opt[kk,jj] = test_result

0
[0. 0. 0. 0. 0.]
1
[0.57 0.   0.   0.   0.  ]
2
[0.57 1.   0.   0.   0.  ]
3
[0.57 1.   1.   0.   0.  ]
4
[0.57 1.   1.   1.   0.  ]


In [19]:
savepkl(np.sum(Agg_root_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_root_opt.pkl')
np.sum(Agg_root_opt==1,axis=1)/nset

array([0.57, 1.  , 1.  , 1.  , 1.  ])

In [15]:
#x^(3/4)_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=3/4)
Agg_third_opt=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    print(np.sum(Agg_third_opt==1,axis=1)/nset)
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result =  Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_third_opt[kk,jj] = test_result

0
[0. 0. 0. 0. 0.]
1
[0.89 0.   0.   0.   0.  ]
2
[0.89 1.   0.   0.   0.  ]
3
[0.89 1.   1.   0.   0.  ]
4
[0.89 1.   1.   1.   0.  ]


In [20]:
savepkl(np.sum(Agg_third_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_third_opt.pkl')
np.sum(Agg_third_opt==1,axis=1)/nset

array([0.89, 1.  , 1.  , 1.  , 1.  ])

In [16]:
#x^(1/4)_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=1/4)
Agg_oneoverfour_opt=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    print(np.sum(Agg_oneoverfour_opt==1,axis=1)/nset)
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result =  Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_oneoverfour_opt[kk,jj] = test_result

0
[0. 0. 0. 0. 0.]
1
[0.16 0.   0.   0.   0.  ]
2
[0.16 0.92 0.   0.   0.  ]
3
[0.16 0.92 0.99 0.   0.  ]
4
[0.16 0.92 0.99 0.96 0.  ]


In [21]:
savepkl(np.sum(Agg_oneoverfour_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_oneoverfour_opt.pkl')
np.sum(Agg_oneoverfour_opt==1,axis=1)/nset

array([0.16, 0.92, 0.99, 0.96, 0.98])

In [17]:
#constant_weight
random.seed(42)
func_weight = function_weight("constant")
Agg_constant_opt=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    print(np.sum(Agg_constant_opt==1,axis=1)/nset)
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result =  Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_constant_opt[kk,jj] = test_result

0
[0. 0. 0. 0. 0.]
1
[0.08 0.   0.   0.   0.  ]
2
[0.08 0.16 0.   0.   0.  ]
3
[0.08 0.16 0.2  0.   0.  ]
4
[0.08 0.16 0.2  0.25 0.  ]


In [22]:
savepkl(np.sum(Agg_constant_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_constant_opt.pkl')
np.sum(Agg_constant_opt==1,axis=1)/nset

array([0.08, 0.16, 0.2 , 0.25, 0.22])

## PD permutation test

In [21]:
random.seed(42)
Perm=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    print(np.sum(Perm<0.05,axis=1)/nset)
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        T_obs, T_perm, p_val = permutation_test(X, Y, num_permutations=1000)
        Perm[kk,jj] = p_val

0
[1. 1. 1. 1. 1.]
1
[0.08 1.   1.   1.   1.  ]
2
[0.08 0.17 1.   1.   1.  ]
3
[0.08 0.17 0.51 1.   1.  ]
4
[0.08 0.17 0.51 1.   1.  ]


In [22]:
savepkl(np.sum(Perm<0.05,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_PD_result.pkl')
np.sum(Perm<0.05,axis=1)/nset 

array([0.08, 0.17, 0.51, 1.  , 1.  ])

## PL permutation test

In [38]:
# convert json (saved as unnamed array) to PL
torus_pllist=[]
for ii in range(len(torus_pd)):
    torus_plsublist = []
    for jj in range(len(torus_pd[ii])):
        torus_pddat = np.array(torus_pd[ii][jj])
        torus_pdmat = np.transpose( np.resize(torus_pddat, (3,int(len(torus_pddat)/3)) ) )
        torus_pdmat = [torus_pdmat[torus_pdmat[:,0]== np.unique(torus_pdmat[:,0])[h],1:] for h in range(len(np.unique(torus_pdmat[:,0])))]
        torus_circle_pl = PersLandscapeApprox(dgms=torus_pdmat, hom_deg=1) # compute persistence landscape
        torus_plsublist.append(torus_circle_pl)
    torus_pllist.append(torus_plsublist)
savepkl(torus_pllist, '../Torus/Torus_PL_list.pkl')

In [36]:
random.seed(42)
PL=np.zeros((nsig,nset))
for kk in range(nsig):
    print(kk)
    for jj in range(nset):
        X = torus_pllist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)]
        Y = torus_pllist[kk][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        PL[kk,jj] =permutation_pl_test(X ,Y) # pvalue 

0
1
2
3
4


In [37]:
savepkl(np.sum(PL<0.05,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_PL_result.pkl')
np.sum(PL<0.05,axis=1)/nset 

array([0.07, 0.31, 1.  , 1.  , 1.  ])

# Simulation with different sample sizes

In [23]:
# simulation parameters
list_npc=[20,40,70,100]
nset=50
sig=[0.01,0.02,0.03,0.04,0.05] #except 0.0
nsig=len(sig)
target_sig_index=1 #sig[1] = 0.02 
random.seed(42)
comb = np.array(list(combinations(range(nset), 2)))
ind=random.sample(range(len(comb)),nset)

## Aggregation test

In [24]:
#linear_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=1)
Agg_linear_opt=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    print(np.sum(Agg_linear_opt==1,axis=1)/nset)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result = Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_linear_opt[n,jj] = test_result

0
[0. 0. 0. 0.]
1
[0.64 0.   0.   0.  ]
2
[0.64 1.   0.   0.  ]
3
[0.64 1.   1.   0.  ]


In [25]:
np.sum(Agg_linear_opt==1,axis=1)/nset 
savepkl(np.sum(Agg_linear_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_linear_opt_diffsamples.pkl')

In [26]:
#root_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=0.5)
Agg_root_opt=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    print(np.sum(Agg_root_opt==1,axis=1)/nset)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result = Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_root_opt[n,jj] = test_result

0
[0. 0. 0. 0.]
1
[0.1 0.  0.  0. ]
2
[0.1  0.96 0.   0.  ]
3
[0.1  0.96 1.   0.  ]


In [27]:
np.sum(Agg_root_opt==1,axis=1)/nset 
savepkl(np.sum(Agg_root_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_root_opt_diffsamples.pkl')

In [28]:
#3/4_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=3/4)
Agg_third_opt=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    print(np.sum(Agg_third_opt==1,axis=1)/nset)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result = Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_third_opt[n,jj] = test_result

0
[0. 0. 0. 0.]
1
[0.24 0.   0.   0.  ]
2
[0.24 1.   0.   0.  ]
3
[0.24 1.   1.   0.  ]


In [29]:
np.sum(Agg_third_opt==1,axis=1)/nset 
savepkl(np.sum(Agg_third_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_third_opt_diffsamples.pkl')

In [30]:
print(np.sum(Agg_third_opt==1,axis=1)/nset )

[0.24 1.   1.   1.  ]


In [31]:
#1/4_weight 
random.seed(42)
func_weight = function_weight("Poly", poly_order=1/4)
Agg_oneoverfour_opt=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    print(np.sum(Agg_oneoverfour_opt==1,axis=1)/nset)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result = Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_oneoverfour_opt[n,jj] = test_result

0
[0. 0. 0. 0.]
1
[0.06 0.   0.   0.  ]
2
[0.06 0.42 0.   0.  ]
3
[0.06 0.42 1.   0.  ]


In [32]:
np.sum(Agg_oneoverfour_opt==1,axis=1)/nset 
savepkl(np.sum(Agg_oneoverfour_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_oneoverfour_opt_diffsamples.pkl')

In [33]:
#constant_weight
random.seed(42)
func_weight = function_weight("constant")
Agg_constant_opt=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    print(np.sum(Agg_constant_opt==1,axis=1)/nset)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        test_result = Aggtest(X,Y,optimal_bandwidths=True,weight_function=func_weight,Rff_approx=True)
        Agg_constant_opt[n,jj] = test_result

0
[0. 0. 0. 0.]
1
[0.04 0.   0.   0.  ]
2
[0.04 0.1  0.   0.  ]
3
[0.04 0.1  0.16 0.  ]


In [34]:
np.sum(Agg_constant_opt==1,axis=1)/nset 
savepkl(np.sum(Agg_constant_opt==1,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_Agg_constant_opt_diffsamples.pkl')

## PD test 

In [34]:
random.seed(42)
Perm=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    print(np.sum(Perm<0.05,axis=1)/nset)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pdlist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pdlist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        T_obs, T_perm, p_val = permutation_test(X, Y, num_permutations=1000)
        Perm[n,jj] = p_val

0
[1. 1. 1. 1.]
1
[0.08 1.   1.   1.  ]
2
[0.08 0.12 1.   1.  ]
3
[0.08 0.12 0.18 1.  ]


In [35]:
savepkl(np.sum(Perm<0.05,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_PD_result_diffsamples.pkl')
np.sum(Perm<0.05,axis=1)/nset 

array([0.08, 0.12, 0.18, 0.34])

## PL test

In [39]:
random.seed(42)
PL=np.zeros((len(list_npc),nset))
for n in range(len(list_npc)):
    print(n)
    npc=list_npc[n]
    for jj in range(nset):
        X = torus_pllist[nsig][npc*(comb[ind[jj]][0]):npc*(comb[ind[jj]][0]+1)] #no-noise
        Y = torus_pllist[target_sig_index][npc*(comb[ind[jj]][1]):npc*(comb[ind[jj]][1]+1)]
        PL[n,jj] =permutation_pl_test(X ,Y) # pvalue 

0
1
2
3


In [ ]:
savepkl(np.sum(PL<0.05,axis=1)/nset, '../../results/simulation_results/Torus_results/Torus_PL_result_diffsamples.pkl')
np.sum(PL<0.05,axis=1)/nset  

In [43]:
np.sum(PL<0.05,axis=1)/nset 

array([0.06, 0.22, 0.52, 0.9 ])

# Type I error simulation

In [35]:
# simulation parameters
npc = 25
nset = 200
sig = [0.01, 0.02, 0.03, 0.04, 0.05]
nsig = len(sig)

target_data = torus_pdlist[nsig]   # no noise
random.seed(40)

selected_pairs = []

for r in range(10):
    group_ids = list(range(nset))
    random.shuffle(group_ids)

    pairs_r = [
        (group_ids[2*j], group_ids[2*j + 1])
        for j in range(nset // 2)
    ]

    selected_pairs.extend(pairs_r)

npair = len(selected_pairs)  # 1000


In [ ]:
print(np.array(selected_pairs).shape)
# (1000, 2)

np.savetxt(
    "selected_pairs_torus_fpr.csv",
    selected_pairs,
    delimiter=",",
    fmt="%d"
)

In [36]:
#linear_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=1)
Agg_linear_opt = np.zeros(npair)
for jj, (g1, g2) in enumerate(selected_pairs):
    if jj%100==0:
        print(jj)
    X = target_data[
        g1 * npc : (g1 + 1) * npc
    ]

    Y = target_data[
        g2 * npc : (g2 + 1) * npc
    ]

    Agg_linear_opt[jj] = Aggtest(
        X,
        Y,
        optimal_bandwidths=True,
        weight_function=func_weight,
        Rff_approx=True
    )

0
100
200
300
400
500
600
700
800
900


In [37]:
print(np.sum(Agg_linear_opt==1)/npair)
savepkl(np.sum(Agg_linear_opt==1)/npair, '../../results/simulation_results/Torus_results/Torus_Agg_linear_opt_validity.pkl')

0.047


In [38]:
#root_weight
random.seed(42)
func_weight = function_weight("Poly", poly_order=1/2)
Agg_root_opt = np.zeros(npair)
for jj, (g1, g2) in enumerate(selected_pairs):
    if jj%100==0:
        print(jj)
    X = target_data[
        g1 * npc : (g1 + 1) * npc
    ]

    Y = target_data[
        g2 * npc : (g2 + 1) * npc
    ]

    Agg_root_opt[jj] = Aggtest(
        X,
        Y,
        optimal_bandwidths=True,
        weight_function=func_weight,
        Rff_approx=True
    )

0
100
200
300
400
500
600
700
800
900


In [39]:
print(np.sum(Agg_root_opt==1)/npair)
savepkl(np.sum(Agg_root_opt==1)/npair, '../../results/simulation_results/Torus_results/Torus_Agg_root_opt_validity.pkl')

0.058


In [40]:
#constant_weight
random.seed(42)
func_weight = function_weight("constant")
Agg_constant_opt = np.zeros(npair)
for jj, (g1, g2) in enumerate(selected_pairs):
    if jj%100==0:
        print(jj)
    X = target_data[
        g1 * npc : (g1 + 1) * npc
    ]

    Y = target_data[
        g2 * npc : (g2 + 1) * npc
    ]

    Agg_constant_opt[jj] = Aggtest(
        X,
        Y,
        optimal_bandwidths=True,
        weight_function=func_weight,
        Rff_approx=True
    )

0
100
200
300
400
500
600
700
800
900


In [41]:
print(np.sum(Agg_constant_opt==1)/npair)
savepkl(np.sum(Agg_constant_opt==1)/npair, '../../results/simulation_results/Torus_results/Torus_Agg_constant_opt_validity.pkl')

0.062


In [36]:
#PD test
random.seed(42)
Perm= np.zeros(npair)
for jj, (g1, g2) in enumerate(selected_pairs):
    if jj%100==0:
        print(jj)
    X = target_data[
        g1 * npc : (g1 + 1) * npc
    ]

    Y = target_data[
        g2 * npc : (g2 + 1) * npc
    ]
    T_obs, T_perm, p_val = permutation_test(X, Y, num_permutations=1000)
    Perm[jj] = p_val

0
100
200
300
400
500
600
700
800
900


In [37]:
print(np.sum(Perm<0.05)/npair) 
savepkl(np.sum(Perm<0.05)/npair, '../../results/simulation_results/Torus_results/Torus_PD_result_validity.pkl')

0.062


In [39]:
#PL test
target_data = torus_pllist[nsig] #not noise
random.seed(42)
PL= np.zeros(npair)
for jj, (g1, g2) in enumerate(selected_pairs):
    if jj%100==0:
        print(jj)
    X = target_data[
        g1 * npc : (g1 + 1) * npc
    ]

    Y = target_data[
        g2 * npc : (g2 + 1) * npc
    ]
    PL[jj] =permutation_pl_test(X ,Y) # pvalue 

0
100
200
300
400
500
600
700
800
900


In [40]:
print(np.sum(PL<0.05)/npair) 
savepkl(np.sum(PL<0.05)/npair, '../../results/simulation_results/Torus_results/Torus_PL_result_validity.pkl')

0.068
